version: '3'
services:
  vscode:
    build: .
    container_name: code-server 
    ports:
      - 8080:8080    
    volumes:
      - ".config:/home/coder/.config"
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8080/ || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s