volumes:
  db: {}

networks:
  sonar:
    external: true
  sonar-internal:
    external: false

services:
  db:
    image: postgres:18-alpine
    container_name: ${PROJECT_NAME}-db
    env_file:
      - .env
    volumes:
      - db:/var/lib/postgresql/data
    networks:
      - sonar-internal

  sonarqube:
    image: sonarqube:26.1.0.118079-community
    container_name: ${PROJECT_NAME}-sonarqube
    ports:
      - 9000:9000
    env_file:
      - .env
    depends_on:
      - db
    networks:
      - sonar
      - sonar-internal
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:9000/api/system/health | grep -q 'ok'"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 90s
