volumes:
    db: {}

services: 
    db:
        container_name: ${PROJECT_NAME}-db
        image: postgres:18.0-alpine
        volumes:
            - db:/var/lib/postgresql/data
        env_file:
            - .env