services: 
    frontend:
        build: ./frontend
        command: sh run-frontend-dev.sh
        volumes: 
            - ./frontend:/frontend
        ports: 
            - 5173:5173
        env_file: 
            - .env