# build stage
FROM node:22 as build-stage
# build stage
WORKDIR /app
ENV VITE_API_URL=VITE_API_URL_PLACEHOLDER
ENV VITE_FRONTEND_URL=VITE_FRONTEND_URL_PLACEHOLDER

COPY ./package.json /app/package.json
COPY ./ /app
RUN ls -la
RUN yarn
RUN yarn build

# production stage
FROM nginx:stable-alpine as production-stage
WORKDIR /app
COPY --from=build-stage /app/dist /app
COPY ./nginx/nginx.conf /etc/nginx/nginx.conf
COPY ./substitute_environment_variables.sh /substitute_environment_variables.sh
RUN chmod +x /substitute_environment_variables.sh
EXPOSE 80
ENTRYPOINT ["/substitute_environment_variables.sh"]
