version: '3.3'

volumes:
    media: {}
    static: {}

services: 
    db:
        container_name: ${PROJECT_NAME}-db
        image: postgres:15.2-alpine
        env_file:
            - .env

    backend:
        container_name: ${PROJECT_NAME}-backend
        build: ./backend
        command: sh runserver.sh
        volumes: 
            - ./backend:/backend
            - media:/var/www/${PROJECT_NAME}/media/
            - static:/var/www/${PROJECT_NAME}/static/
        env_file: 
            - .env

    nginx:
        container_name: ${PROJECT_NAME}-nginx
        image: nginx:1.25.2
        ports:
            - 8000:8000
        volumes:
            - ./config/nginx.conf:/etc/nginx/conf.d/default.conf
            - media:/var/www/${PROJECT_NAME}/media/
            - static:/var/www/${PROJECT_NAME}/static/
        env_file:
            - .env
        environment:
            NGINX_ENVSUBST_TEMPLATE_SUFFIX: ".conf"