services:
  postgres:
    image: postgres:18-alpine
    container_name: n8n_postgres
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -h localhost -U ${POSTGRES_USER} -d ${POSTGRES_DB}']
      interval: 5s
      timeout: 5s
      retries: 10

  n8n:
    image: n8nio/n8n:1.123.30
    container_name: n8n
    restart: unless-stopped
    ports:
      - "5678:5678"
    env_file:
      - .env
    volumes:
      - n8n_data:/home/node/.n8n
      - ./n8n/hooks.js:/home/node/.n8n/hooks.js

    depends_on:
      postgres:
        condition: service_healthy

volumes:
  postgres_data:
    name: n8n_postgres_data
  n8n_data:
    name: n8n_data