version: '3'
networks:
    proxy:
        external:
            name: proxy
services:
    proxy:
        image: traefik:alpine # The official Traefik docker image
        command: --docker
        networks:
            - proxy
        ports:
            - "80:80"
            - "443:443"
            - "8080:8080" # dashboard
        volumes:
            -  "./config/traefik.toml:/traefik.toml"
            -  "./acme.json:/acme.json"
            - /var/run/docker.sock:/var/run/docker.sock
        restart: always
        labels:
            - "traefik.frontend.rule=Host:traefik.<DOMAIN>"
            - "traefik.port=8080"
            - "traefik.backend=traefik"
            - "traefik.frontend.entryPoints=http,https"

