services: 
    jupyter:
        container_name: ${PROJECT_NAME}-jupyter
        build: ./jupyter
        command: sh run-jupyter.sh
        volumes: 
            - ./jupyter:/jupyter
        ports: 
            - 8888:8888
        env_file: 
            - .env