version: "3.9"

volumes:
  db: {}

services:  
  db:
    container_name: label-studio-db
    image: postgres:17-alpine
    hostname: db
    restart: always
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
      - db:/var/lib/postgresql/data

  app:
    container_name: label-studio-app
    image: heartexlabs/label-studio:20240926.221338-develop-056e48992
    ports:
      - 18080:8080
    depends_on:
      - db
    env_file:
      - .env
    volumes:
      - ./data:/label-studio/data:rw