volumes:
    db-superset: {}

services: 
    redis:
        container_name: ${PROJECT_NAME}-redis
        image: redis:7.2-alpine
        volumes:
            - redis_db:/data
        ports:
            - 6379:6379
            
    superset-db:
        container_name: ${PROJECT_NAME}-superset-db
        image: postgres:17-alpine
        volumes:
            - db-superset:/var/lib/postgresql/data
        env_file:
            - .env
        environment:
            POSTGRES_USER: "${POSTGRES_SUPERSET_USER}"
            POSTGRES_PASSWORD: "${POSTGRES_SUPERSET_PASSWORD}"
            POSTGRES_DB: "${POSTGRES_SUPERSET_DB}"
        
    superset:
        image: amancevice/superset:4.1.0
        container_name: ${PROJECT_NAME}-superset
        volumes:
          - ./superset:/home/superset/script
        ports:
            - "8088:8088"
        env_file:
            - .env
        command: bash /home/superset/script/run.sh