volumes:
    loki_data: {}
    grafana_data: {}

services:
    loki:
        image: grafana/loki:3.3.2
        volumes:
            - loki_data:/loki

    grafana:
        image: grafana/grafana:11.4.0
        volumes:
          - grafana_data:/var/lib/grafana
        ports:
            - 3000:3000