volumes:
    log: {}
services:
    nginx:
        image: nginx:1.25.2
        container_name: ${PROJECT_NAME}-nginx
        ports:
            - 8000:8000
            - 8080:8080
        volumes:
            - ./config/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
            - log:/var/log/nginx/
        environment:
            NGINX_ENVSUBST_TEMPLATE_SUFFIX: ".conf"

    promtail:
        image: grafana/promtail:2.5.0
        volumes:
            - ./config/promtail/promtail.yaml:/etc/promtail/promtail.yaml
            -  log:/var/log/nginx/
        command: --config.file=/etc/promtail/promtail.yaml
        healthcheck:
          test: ["CMD-SHELL", "curl -f http://localhost:9080/ready || exit 1"]
          interval: 30s
          timeout: 10s
          retries: 3
          start_period: 20s