volumes:
    media: {}
    static: {}

services: 
    nginx:
        container_name: ${PROJECT_NAME}-nginx
        image: nginx:1.25.2-alpine
        ports:
            - 8000:8000
            - 8080:8080
        volumes:
            - ./config/nginx.conf:/etc/nginx/conf.d/default.conf
            - media:/var/www/media/
            - static:/var/www/static/
        env_file:
            - .env
        environment:
            NGINX_ENVSUBST_TEMPLATE_SUFFIX: ".conf"