volumes:
    media: {}
    static: {}

services: 
    nginx:
        container_name: ${PROJECT_NAME}-backend
        image: nginx:1.25.2-alpine
        ports:
            - 8000:8000
            - 8080:8080
        volumes:
            - ./config/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
            - log:/var/log/nginx/
            - media:/var/www/${PROJECT_NAME}/media/
            - static:/var/www/${PROJECT_NAME}/static/
        env_file:
            - .env
        environment:
            NGINX_ENVSUBST_TEMPLATE_SUFFIX: ".conf"