[databases]
db1 = host=db1 port=5432 dbname=database01
db2 = host=db2 port=5432 dbname=database02

[pgbouncer]
listen_addr = *
listen_port = 6432
auth_type = scram-sha-256
auth_file = /etc/pgbouncer/userlist.txt

# Automated DB User Lookup
auth_user = pgbouncer_auth
auth_query = SELECT uname, phash FROM user_lookup($1)

# Pooling configuration
pool_mode = transaction
max_client_conn = 1000
default_pool_size = 20