volumes:
    media: {}
    static: {}
    db: {}

services: 
    db:
        container_name: ${PROJECT_NAME}-db
        image: postgres:16.3-alpine
        volumes:
          - db:/var/lib/postgresql/data
        env_file:
            - .env
    backend:
        container_name: ${PROJECT_NAME}-backend
        build: ./backend
        command: sh runserver-dev.sh
        volumes: 
            - ./backend:/backend
            - media:/var/www/media/
            - static:/var/www/static/
        ports: 
            - 8000:8000
        env_file: 
            - .env