volumes:
    media: {}
    static: {}
    db: {}

services: 
    db:
        container_name: ${PROJECT_NAME}-db
        image: postgres:15.2-alpine
        volumes:
          - db:/var/lib/postgresql/data
        env_file:
            - .env
    backend:
        container_name: ${PROJECT_NAME}-backend
        build: ./backend
        command: sh runserver.sh 4
        volumes: 
            - ./backend:/backend
            - media:/var/www/${PROJECT_NAME}/media/
            - static:/var/www/${PROJECT_NAME}/static/
        ports: 
            - 8000:8000
        env_file: 
            - .env