version: '3.3'
services: 
    frontend:
        container_name: ${PROJECT_NAME}-frontend
        build: ./frontend
        command: sh run_frontend.sh
        volumes: 
            - ./frontend:/frontend
        ports: 
            - 5173:5173
        env_file: 
            - .env