volumes:
    data: {}
services:
    minio:
        container_name: minio-minio
        image: quay.io/minio/minio:RELEASE.2022-02-18T01-50-10Z
        command: server /data/minio1/ --console-address ":9001" 
        ports:
            - 9000:9000
            - 9001:9001
        environment:
            MINIO_ROOT_USER: minio
            MINIO_ROOT_PASSWORD: minio123
        volumes:
            - data:/data