services:
    zap-web:
        image: zaproxy/zap-stable:2.16.0
        command: bash run-zap-web.sh
        environment:
            - PYTHONUNBUFFERED=1
        volumes:
          - ./output:/zap/wrk
          - ./config/run-zap-web.sh:/zap/run-zap-web.sh
        healthcheck:
          test: ["CMD-SHELL", "curl -f http://localhost:8090/ || exit 1"]
          interval: 30s
          timeout: 10s
          retries: 3
          start_period: 120s