volumes:
  redis_db: {}
services: 
    redis:
        container_name: ${PROJECT_NAME}-redis
        image: redis/redis-stack-server:6.2.6-v7
        volumes:
            - redis_db:/data
        ports:
            - 6379:6379 
        env_file:
            - .env
    
    redis-insight:
        container_name: ${PROJECT_NAME}-redis-insight
        image: redislabs/redisinsight:1.13.1
        env_file:
            - .env
        ports:
            - 8001:8001