volumes:
    redis_db: {}
services:
    redis:
        container_name: ${PROJECT_NAME}-redis
        image: redis:7.2
        volumes:
            - redis_db:/data
        ports:
            - 6379:6379